name: Build Extension Bundle

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Package extension
        run: bun run package

      - name: Upload extension bundle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-tool-extension-bundle
          path: screenshot-tool-extension.zip
          retention-days: 1
