name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to tags matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Package extension
        run: bun run package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-tool-extension
          path: screenshot-tool-extension.zip
          retention-days: 7

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: screenshot-tool-extension

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: screenshot-tool-extension.zip
          generate_release_notes: true
          draft: false
