name: Build Release Artifact

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Package extension
        run: bun run package

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: screenshot-tool-extension.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: screenshot-tool-extension.zip
          generate_release_notes: true
          draft: false
